### ISSUE TITLE
Rate limit violating twitter api limits

### ISSUE THREAD

**Issue by dakisback2** [Alexhuszagh/blockbot#1]
The script sleeps to avoid twitter api limits however it is not aggressive enough. I think the limit for twitter is 50 blocks per 15 minutes. It doesn't sleep until 300 blocks in my experience; at that point your twitter app says: This App has violated Twitter Rules and policies. As a result, certain functions will be limited.

**Comment by Alexhuszagh** [comment]
That might be very new, it used to be a pretty generic number of rate limits. I've used this more than 50 blocks/15m on well, for at least 25k blocks in the past. Let me check if there's any new API updates on this. I used to get like ~300-500 blocks every 15 min.

**Comment by dakisback2** [comment]
Thanks for getting back to me quickly! 

it's my first time using this project. However I noticed after my first 150 it blocked my app.

At least in this documentation it says 50. Could probably get away with more but I'm basically having to manually restart it with a new api app every time.

https://developer.twitter.com/en/docs/twitter-api/rate-limits

**Comment by Alexhuszagh** [comment]
Ok yep, that's the new APIv2 limits from Twitter (which still should be in early access), this didn't used to be the case. I can add a manual rate limiter for specific actions, since Tweepy doesn't seem to support this yet.

The old rate [limits](https://developer.twitter.com/en/docs/twitter-api/v1/rate-limits) were quite different and much more amenable to a tool like this...

**Comment by Alexhuszagh** [comment]
Ok I've got an initial prototype working. I still want to see if there's going to be support for v1.1 of the API, because it's so much more amenable to anti-abuse tool like this.

> Follows lookup | 15 | 15

That and the 50 blocks per 15 minute window makes most of this functionality **very** slow...

**Comment by dakisback2** [comment]
> Ok I've got an initial prototype working. I still want to see if there's going to be support for v1.1 of the API, because it's so much more amenable to anti-abuse tool like this.
> 
> > Follows lookup | 15 | 15
> 
> That and the 50 blocks per 15 minute window makes most of this functionality **very** slow...

Thank you! I'm assuming I need to do something special to use this functionality? I just cloned it and ran setup.py and tried again and it blocked about 150 and my app got shut down.

**Comment by Alexhuszagh** [comment]
Sorry the initial prototype hasn't been posted, I'm working out the issues and will update with the new way to ensure the rate limits are working. Give me a bit.

**Comment by Alexhuszagh** [comment]
Can you post the result of the following:

```python
from blockbot.api import generate_api
api = generate_api()
print(api.api_root)
```

It should give a value of `/1.1`, or `/v2`. I'm expecting the result to be `v1.1` but you to still be limited to the `/v2` rate limits, which seems less than ideal...

**Comment by Alexhuszagh** [comment]
Ok this has been fixed as of the latest commit. To use the new rate limits, you should do if using a config file:

```json
{
    "consumer_key": "AIbwRVbCJMkaiQVlfJbKG5gAy",
    "consumer_secret": "P0wiBhrdNlCTb2okvzxRGNKD4opnyOtFGM7Q6Hvmig0IzjMYw5",
    "access_token": "Q9D4wOv9zA-q3rlIxbZgknaZKaPwGBPtiT4AcQLWZ5Q9lduhX7",
    "access_token_secret": "lXyoz2kDkSz01riCAkbOlE4iOmSkBlHXVij",
    "api_root": "/2",
    "local_rate_limit": true
}
```

If manually specifying parameters to the function, you can do:

```python
import blockbot

account_screen_names = ['twitter']
whitelist_screen_names = ['jack']
blockbot.block_followers(account_screen_names, whitelist_screen_names, api_root='/2', local_rate_limit=True)
```

Please note that this should be substantially slower than the regular API limit, but it uses a FIFO queue to ensure that rate limits aren't exceeded, using local rate limiting (while also using Tweepy's warn on rate limit as a backup).

**Comment by dakisback2** [comment]
Just FYI I'm not the best for debugging since I'm not super savvy with this thing. However I did add that to my config file and I'm getting the following error:

2021-09-13 13:49:37,750 - BlockFollowers - INFO - Blocked follower=***********
2021-09-13 13:49:37,857 - Daemon - CRITICAL - name 'interval' is not defined

Here's my api.json

![image](https://user-images.githubusercontent.com/90546900/133155092-49d11617-bb1b-4d17-8a1d-083d334b8b25.png)

**Comment by Alexhuszagh** [comment]
That's my bug, the latest commit should fix that :// Let me know if there are any other bugs. Your config file is correct.

**Comment by dakisback2** [comment]
Thank you! I think it's working great now! I'm tailing the log. I'll reply back if we have any issues!

Now to wait a few months to block 860,000 accounts 💀

**Comment by dakisback2** [comment]
It's still messing up after a few times. I'm gonna change it to 45 blocks per 15 minutes and see if that helps. Twitter... 🤦 Will be like 24 hours though since I can't make a new api app since I can only make 3 per day.

**Comment by Alexhuszagh** [comment]
Weird, maybe the rate limits are slightly off. It's queued so it makes at maximum 50 requests/15 min, but it's possible Twitter has lower caps per day.

**Comment by dakisback2** [comment]
Yeah I see it looks perfect. My only guess is somehow the "BlockFollowers - INFO - Already blocked follower=" might be adding into that number? I'll be able to test more and see if less blocks works.

I've only been able to block about 110 before it dies

**Comment by Alexhuszagh** [comment]
> Yeah I see it looks perfect. My only guess is somehow the "BlockFollowers - INFO - Already blocked follower=" might be adding into that number? I'll be able to test more and see if less blocks works.
> 
> I've only been able to block about 110 before it dies

It shouldn't be, since it isn't calling `create_block` for that. It basically queries a local database (you can view it yourself if you want), which memoizes all the blocked users to ensure that minimal API calls are made. There might be another rate limit, however, that's the issue. Tweepy doesn't return HTTP header information though, so it's hard to tell.

https://github.com/Alexhuszagh/blockbot/blob/e6167e5d7488268fe484d0e699856523470140b6/blockbot/block_followers.py#L129-L139

**Comment by dakisback2** [comment]
Thanks!! I still don't see anything about why it's not working. Reduced numbers in the local rate limit don't seem to work either. I posted on the developer forums and no response ye.

**Comment by dakisback2** [comment]
Good news. Your local rate limiting appears to work out of the box now. I've been running it for 45 minutes now.

Twitter support got back to me and their automated systems were blocking my app.

`Twitter has automated systems that find and disable abusive API keys in bulk. Unfortunately, it looks like your application got caught up in one of these spam groups by mistake. We have reactivated the API key and we apologize for the inconvenience. 

Regards,
Twitter Platform Operations`
